import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const theme = JSON.parse(readFileSync(resolve(root, "app/theme.json"), "utf8"));

function rgb(hex) {
  const normalized = hex.replace("#", "");
  if (!/^[0-9a-f]{6}$/i.test(normalized)) throw new Error(`Invalid six-digit hex colour: ${hex}`);
  return [0, 2, 4].map((offset) => Number.parseInt(normalized.slice(offset, offset + 2), 16)).join(" ");
}

const css = `/* AUTO-GENERATED from app/theme.json. Do not edit this file directly. */

:root {
  /* Core palette — edit app/theme.json */
  --color-paper-rgb: ${rgb(theme.paper)};
  --color-ink-rgb: ${rgb(theme.ink)};
  --color-accent-rgb: ${rgb(theme.accent)};
  --color-white-rgb: ${rgb(theme.white)};
  --color-dark-rgb: ${rgb(theme.dark)};
  --color-ticket-dark-rgb: ${rgb(theme.ticketDark)};

  --color-paper: rgb(var(--color-paper-rgb));
  --color-ink: rgb(var(--color-ink-rgb));
  --color-accent: rgb(var(--color-accent-rgb));
  --color-white: rgb(var(--color-white-rgb));
  --color-dark: rgb(var(--color-dark-rgb));
  --color-ticket-dark: rgb(var(--color-ticket-dark-rgb));

  /* Derived surfaces and lines */
  --color-paper-50: rgb(var(--color-paper-rgb) / 0.5);
  --color-ink-03: rgb(var(--color-ink-rgb) / 0.03);
  --color-ink-18: rgb(var(--color-ink-rgb) / 0.18);
  --color-ink-35: rgb(var(--color-ink-rgb) / 0.35);
  --color-ink-58: rgb(var(--color-dark-rgb) / 0.58);
  --color-ink-75: rgb(var(--color-dark-rgb) / 0.75);
  --color-white-70: rgb(var(--color-white-rgb) / 0.7);

  --color-line: var(--color-ink-18);
  --color-line-strong: var(--color-ink-35);
  --color-overlay-hover: var(--color-ink-03);
  --color-light-muted: var(--color-white-70);
  --color-dark-line: #333;
  --color-ticket-line: #484848;
  --color-control-line: #555;
  --color-text-muted: #555;
  --color-placeholder: #76736c;
  --color-text-subtle: #777;
  --color-ticket-copy: #aaa;
  --color-ticket-footnote: #888;
  --color-disabled: #666;
  --color-feature-copy: #221100;

  /* Shared gradient colour recipes. Geometry/placement is in gradients.css. */
  --paper-orb-gradient: radial-gradient(
    ellipse 50% 50% at 50% 50%,
    rgb(var(--color-accent-rgb) / 1) 0%,
    rgb(var(--color-accent-rgb) / 1) 24%,
    rgb(var(--color-accent-rgb) / 0.783) 48%,
    rgb(var(--color-accent-rgb) / 0.405) 64%,
    rgb(var(--color-accent-rgb) / 0.162) 74%,
    transparent 86%
  );

  --dark-orb-gradient: radial-gradient(
    circle at 50% 50%,
    rgb(var(--color-accent-rgb) / 0.5) 0%,
    rgb(var(--color-accent-rgb) / 0.36) 18%,
    rgb(var(--color-accent-rgb) / 0.2) 36%,
    rgb(var(--color-accent-rgb) / 0.09) 52%,
    rgb(var(--color-accent-rgb) / 0.025) 66%,
    transparent 74%
  );

  --paper-glow-opacity: 0.94;
  --hero-glow-blur-mobile: 44px;
  --hero-glow-blur-desktop: 54px;
}
`;

writeFileSync(resolve(root, "app/theme.generated.css"), css);
console.log("Generated app/theme.generated.css from app/theme.json.");
